// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuscisuftxwurjfbnmnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1c2Npc3VmdHh3dXJqZmJubW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMTAxODcsImV4cCI6MjA3NDY4NjE4N30.MGANpkQ3sfjHONTqky1y3BO3UA0wwtm4fgCi5tYF9Ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});